donate_app/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
app_name=  'donate_app'
urlpatterns = [
    path('', home, name='home'),
    # path('donateview/', donateview, name='donateview'),
    path('donateform/', donateform, name='donateform'),
    path('add/', adddonation, name='adddonation'),
    path('team/', team, name='team'),
    path('what/', what, name='what'),
    path('contact/', contact, name='contact'),
    path('shop/', shop, name='shop'),
    path('blogs/', blogs, name='blogs'),
    path('faq/', faq, name='faq'),

    
]

pariwartan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from donate_app.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('donate/', include('donate_app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from user_app.views import signup, signupform, loginauth
app_name = 'user_app'

urlpatterns = [
    path('signupform/', signupform, name='signupform'),
    path('signup/', signup, name='signup'),
    path('login/', loginauth, name='login'),
    
]

donate_app/models.py
from django.db import models

# Create your models here.

class DateCategoryModel(models.Model):
    cat_title = models.CharField(max_length=120)

    def __str__(self):
        return(self.cat_title)

# GENDER_MALE = 0
# GENDER_FEMALE = 1
# GENDER_NOT_SPECIFIED = 2

# GENDER_CHOICES = [(GENDER_MALE, 'Male'), (GENDER_FEMALE, 'Female')]

class DonateModel(models.Model):
    name = models.CharField(max_length=255)
    contact = models.CharField(max_length=120)
    address = models.CharField(max_length=255)
    datecategory = models.ForeignKey(DateCategoryModel,on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return(self.name)

user_app/models.py
from django.db import models

# Create your models here.

GENDER_MALE = 0
GENDER_FEMALE = 1
GENDER_NOT_SPECIFIED = 2

GENDER_CHOICES = [(GENDER_MALE, 'Male'), (GENDER_FEMALE, 'Female')]

class UserModel(models.Model):
    name = models.CharField(max_length=120) 
    email = models.EmailField()
    gender = models.IntegerField(choices=GENDER_CHOICES, default=GENDER_NOT_SPECIFIED)
    password = models.CharField(max_length=120)

    def __str__(self):
        return(self.name)

donate_app/forms.py
from django import forms 
from .models import DateCategoryModel, DonateModel

class DonateForm(forms.ModelForm):
    class Meta:
        model = DonateModel
        fields = '__all__'
    # name = forms.CharField(label='name', max_length=255)
    # contact = forms.CharField(label='contact', max_length=120)
    # address = forms.CharField(label='address', max_length=255)
    # datecategory = forms.ForeignKey(DateCategoryModel,on_delete=models.CASCADE)
    # timestamp = froms.DateTimeField(auto_now_add=True)

user_app/forms.py
from django import forms 
from .models import UserModel

class UserForm(forms.ModelForm):
    class Meta:
        model = UserModel
        fields = '__all__'

donate_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import DonateForm
from django.views.generic import *

# Create your views here.


# class HomeView(TemplateView):
#     template_name = 'index.html'

def home(requests):
    return render(requests, 'index.html')

# def donateview(requests):
#     return render(requests, 'Donate.html')

def donateform(requests):
    form = DonateForm()
    context = {'form' : form}
    return render(requests, 'donation_form.html', context)

def adddonation(request):
    if(request.method == 'POST'):
        form = DonateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('donate_app:home')
            # try:
            # except:
            #     return HttpResponse('Failed')
        else:
            print(form.errors)
            return HttpResponse('Form not Valid')
    else:
        # form = QuestionForm
        datecategory = DateCategoryModel.objects.all()
        return render(request, 'questionmodel_create.html', {'datecategory':datecategory})

def team(request):
    return render(request, 'team.html')

def what(request):
    return render(request, 'what.html')

def contact(request):
    return render(request, 'contact.html')

def shop(request):
    return render(request, 'shop.html')

def blogs(request):
    return render(request, 'blogs.html')

def faq(request):
    return render(request, 'FAQ.html')

user_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from user_app.models import UserModel
from user_app.forms import UserForm

# Create your views here.

def signupform(request):
    form = UserForm()
    context={'form':form}
    return render(request, 'signup.html', context)

def signup(request):

      if(request.method == 'POST'):
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('donate_app:donateform')
        else:
            print(form.errors)
            return HttpResponse('Form not Valid') 

def loginauth(request):
    if request.method == "POST":
        e = request.POST.get('email')
        p = request.POST.get('pass')
        users = UserModel.objects.filter(email=e, password=p)
        if(users.count() > 0):
            for user in users:
                request.session['email'] = user.email
                request.session['id'] = user.id
                request.session['name'] = user.name
                return redirect('home')
        else:
            return HttpResponse('Wrong Credentials')
    else:
        return render(request, 'login.html')

donate_app/templates/Blogs.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Pariwartan | Blogs
{% endblock %}

{% block navbar %}
	<ul>
		<li ><a href="{% url 'donate_app:home' %}">Home</a></li>	
		<li ><a href="{% url 'donate_app:what' %}">What we do</a></li>	
		<li ><a href="{% url 'donate_app:donateform' %}">Donate</a></li>
		<li><a href="{% url 'donate_app:shop' %}">Shop</a></li>
        <li class="active"><a href="{% url 'donate_app:blogs' %}">Blogs</a></li>
        <li ><a href="{% url 'donate_app:contact' %}">Contact Us</a></li>
		<li ><a href="{% url 'donate_app:faq' %}">FAQ</a></li>
		<li ><a href="{% url 'donate_app:team' %}">Our team</a></li>
		<li><a href="{% url 'user_app:login' %}"><button>Log in</button></a>
		<li><a href="{% url 'user_app:signupform' %}"><button>Sign up</button></a>

    </ul>
{% endblock %}

{% block media_content %}
<div class="middle">
</div>
{% endblock %}

donate_app/templates/Contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Pariwartan | Contact
{% endblock%}

{% block navbar %}
	<ul>
		<li ><a href="{% url 'donate_app:home' %}">Home</a></li>	
		<li ><a href="{% url 'donate_app:what' %}">What we do</a></li>	
		<li ><a href="{% url 'donate_app:donateform' %}">Donate</a></li>
		<li><a href="{% url 'donate_app:shop' %}">Shop</a></li>
        <li ><a href="{% url 'donate_app:blogs' %}">Blogs</a></li>
        <li class="active"><a href="{% url 'donate_app:contact' %}">Contact Us</a></li>
		<li ><a href="{% url 'donate_app:faq' %}">FAQ</a></li>
		<li ><a href="{% url 'donate_app:team' %}">Our team</a></li>
		<li><a href="{% url 'user_app:login' %}"><button>Log in</button></a>
		<li><a href="{% url 'user_app:signupform' %}"><button>Sign up</button></a>

    </ul>
{% endblock %}

{% block media_content %}
<div class="middle">
</div>
{% endblock %}

donate_app/templates/FAQ.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Pariwartan | FAQ
{% endblock %}

	{% block navbar %}
	<ul>
		<li ><a href="{% url 'donate_app:home' %}">Home</a></li>	
		<li ><a href="{% url 'donate_app:what' %}">What we do</a></li>	
		<li ><a href="{% url 'donate_app:donateform' %}">Donate</a></li>
		<li ><a href="{% url 'donate_app:shop' %}">Shop</a></li>
		<li ><a href="{% url 'donate_app:blogs' %}">Blogs</a></li>
		<li ><a href="{% url 'donate_app:contact' %}">Contact Us</a></li>
		<li class="active"><a href="{% url 'donate_app:faq' %}">FAQ</a></li>
		<li ><a href="{% url 'donate_app:team' %}">Our team</a></li>
		<li><a href="{% url 'user_app:login' %}"><button>Log in</button></a>
		<li><a href="{% url 'user_app:signupform' %}"><button>Sign up</button></a>
	  
	</ul>
	{% endblock %}

{% block media_content%}
<div class="middle">
</div>
{% endblock %}

donate_app/templates/What.html
{% extends 'base.html' %}
{% load static %}

{% block css%}
	<link rel="stylesheet" type="text/css" href="{% static 'css/styler.css' %}">
{% endblock%}
{% block title %}
Pariwartan | What To Do
{% endblock%}

{% block navbar %}
<ul>
	<li ><a href="{% url 'donate_app:home' %}">Home</a></li>	
	<li class="active"><a href="{% url 'donate_app:what' %}">What we do</a></li>	
	<li ><a href="{% url 'donate_app:donateform' %}">Donate</a></li>
	<li ><a href="{% url 'donate_app:shop' %}">Shop</a></li>
	<li ><a href="{% url 'donate_app:blogs' %}">Blogs</a></li>
	<li ><a href="{% url 'donate_app:contact' %}">Contact Us</a></li>
	<li ><a href="{% url 'donate_app:faq' %}">FAQ</a></li>
	<li ><a href="{% url 'donate_app:team' %}">Our team</a></li>
	<li><a href="{% url 'user_app:login' %}"><button>Log in</button></a>
	<li><a href="{% url 'user_app:signupform' %}"><button>Sign up</button></a>
</ul>
{% endblock %}

{% block media_content %}
<div class="middle">
	<h1>WHO ARE WE?

	</h1>
	<h2>We are a group of young enthusiast who deeply care for the society and are willing to rise by raising others.As a responsible member of the society,we have taken initiatives to help the economically marginalized group of people.
		Pariwartan is a  non-profitable startup completlty focusing on the betterment of the economically backward group of people.We are here to help people donate more clothes easily.With a team of highly dedicated workers,the best shall be done with your donation.
	</h2>
	<br>
	<h1>WHY WE STARTED?</h1>
	<h2>The innovative idea of clothes bank was highly appreciated by many people.People who have clothes that are no longer useful to them so they cameby and donated it to the clothes bank.There are currently three clothes bank in Kathmandu.So despite already having clothes bank, did we choose to build an online platform to it?
		a)For the people who are willing but don't have time to go till the clothes bank.
		b)Number of clothes bank are very  far being just a few (3 places in the kathmandu valley and just a total of six in the whole country)
		c)Not feasible to go till the clothes bank carrying that heavy loads of clothes.
		d)Because its just a click away.
	</h2>
	<br>
	<h1> HOW IT WORKS?</h1>
	<h2>The clothes you donate will first be collected at our warehouse.The clothes that can be redesigned will be  sorted first and then the rest will go for donation.The redesigned clothes will be displayed in our site and people can buy it from there as a social cause by wearing recycled clothes.</h2>
	<br>
</div>
{% endblock %}

donate_app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>
		{% block title %}
			Pariwartan
		{% endblock %}
	</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/styler.css' %}">
    {% block css %}
    
    {% endblock %}
</head>
<body>
<div class="main">

<!--NAVIGATION BAR TOP-->
<div class="navtop">
	<div class="logo">
	<img src="../../media/donateApp/logo.png">
    </div>
    {% block navbar %}
	<ul>
		<li class="active"><a href="{% url 'donate_app:home' %}">Home</a></li>	
		<li ><a href="{% url 'donate_app:what' %}">What we do</a></li>	
		<li ><a href="{% url 'donate_app:donateform' %}">Donate</a></li>
		<li><a href="{% url 'donate_app:shop' %}">Shop</a></li>
        <li ><a href="{% url 'donate_app:blogs' %}">Blogs</a></li>
        <li ><a href="{% url 'donate_app:contact' %}">Contact Us</a></li>
		<li ><a href="{% url 'donate_app:faq' %}">FAQ</a></li>
		<li ><a href="{% url 'donate_app:team' %}">Our team</a></li>
		<a href="{% url 'donate_app:donateform' %}"><button type="button">Donate</button></a>
		<li><a href="{% url 'user_app:login' %}"><button>Log in</button></a>
		<li><a href="{% url 'user_app:signupform' %}"><button>Sign up</button></a>

    </ul>
    {% endblock %}
</div>

{% block media_content %}
<div class="mid">
<div class="background">
	</div>
	</div>
{% endblock %}

	<!--NAVIGATION BAR BOTTOM-->
	<div class="navdown">
		<div class="navdown">
		<ul>	
		<li><a href="#">Terms&Conditions</a></li>
        <li><a href="#">Privacy</a></li>
    </ul>
	</div>
</div>
</body>
</html>

donate_app/templates/donation_form.html
{% extends 'base.html' %}
{% load static%}
          
{% block title %} 
  Donation Form
{% endblock %}

{% block css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/donation_form.css' %}">
{% endblock %}

        <tr>
        <td>
          <label for="name"> <b>Name:</b></label>
          <input type="text" placeholder="Enter your name" name="Name" required> 
        </td>
        </tr>
{% block navbar %}
<ul>
  <li ><a href="{% url 'donate_app:home' %}">Home</a></li>	
  <li ><a href="{% url 'donate_app:what' %}">What we do</a></li>	
  <li class="active"><a href="{% url 'donate_app:donateform' %}">Donate</a></li>
  <li ><a href="{% url 'donate_app:shop' %}">Shop</a></li>
  <li ><a href="{% url 'donate_app:blogs' %}">Blogs</a></li>
  <li ><a href="{% url 'donate_app:contact' %}">Contact Us</a></li>
  <li ><a href="{% url 'donate_app:faq' %}">FAQ</a></li>
  <li ><a href="{% url 'donate_app:team' %}">Our team</a></li>
  <li><a href="{% url 'user_app:login' %}"><button>Log in</button></a>
  <li><a href="{% url 'user_app:signupform' %}"><button>Sign up</button></a>

</ul>
{% endblock %}
 
{% block media_content %}
  <form action="{% url 'donate_app:adddonation' %}" method="POST">
    {% csrf_token %}
    <!-- <table>
      <div class="container">
        <h1>Donation Form</h1>

        <tr>
          <td>
            <label for="name"> <b>Name:</b></label>
            <input type="text" placeholder="Enter your name" name="name" required>
          </td>
        </tr>

                    
        <tr>
          <td>
           <label for="contact"><b>Contact:</b></label>
           <input type="text" placeholder="Enter your contact number" name="contact" required>
          </td>
        </tr>

        
          
        <tr>
          <td>
            <label for="add"><b>Address:</b></label>
            <input type="text" placeholder="Enter your address" name="address" required>
          </td>
        </tr>
      
        <tr>
          <td>
            <label for="date"><b>Date:</b></label>
            <input type="date"  name="date" required>
          </td>
        </tr>


        <tr>
          <td><button type="submit" class="registerbtn">Register</button></td>
        </tr>

      </div>
        
    </table> -->
      
      {{form.as_table}}
      <button type="submit">submit</button>
  </form> 
  
{% endblock %}

</body>
</html>

donate_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
	Pariwartan | HomePage
{% endblock %}

	{% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/styler.css' %}">
	{% endblock %}



{% block navbar %}
<ul>
	<li ><a href="{% url 'donate_app:home' %}">Home</a></li>	
	<li ><a href="{% url 'donate_app:what' %}">What we do</a></li>	
	<li ><a href="{% url 'donate_app:donateform' %}">Donate</a></li>
	<li ><a href="{% url 'donate_app:shop' %}">Shop</a></li>
	<li ><a href="{% url 'donate_app:blogs' %}">Blogs</a></li>
	<li ><a href="{% url 'donate_app:contact' %}">Contact Us</a></li>
	<li class="active"><a href="{% url 'donate_app:faq' %}">FAQ</a></li>
	<li ><a href="{% url 'donate_app:team' %}">Our team</a></li>
	<li><a href="{% url 'user_app:login' %}"><button>Log in</button></a>
	<li><a href="{% url 'user_app:signupform' %}"><button>Sign up</button></a>
</ul>
{% endblock %}

{% block media_content %}
<div class="mid">
	<div class="background">
		<div class="title">
			<h1 style="color: white;">“हजुरको सानो सहयोगले कसैको जिवनमा परिवर्तन ल्याउन सक्छ”</h1>
			<h2 style="color: white;">Do you have old clothes just taking up the space of your cupboard?

				There are more than 25.2% of Nepali People waiting for you to donate a drop from your ocean of clothes.
					
				And what’s more we are at your doorsteps to pick up the clothes that  they need.
					
				Having a Big heart has never been so easy.
				Just fill our donation form  and you have become an aider to their lives.
					
				Do you wanna flex everyone that you wore the stylish Redecorated Garments?.Shop here.
			</h2>
		</div>
	</div>
</div>

{% endblock %}

donate_app/templates/shop.html
{% extends 'base.html' %}
{% load static %}

	{% block title %}
	Pariwartan | Shop
	{% endblock%}

	{% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/shop.css' %} ">
	{% endblock%}


	{% block navbar %}
	<ul>
		<li ><a href="{% url 'donate_app:home' %}">Home</a></li>	
		<li ><a href="{% url 'donate_app:what' %}">What we do</a></li>	
		<li ><a href="{% url 'donate_app:donateform' %}">Donate</a></li>
		<li class="active"><a href="{% url 'donate_app:shop' %}">Shop</a></li>
		<li ><a href="{% url 'donate_app:blogs' %}">Blogs</a></li>
		<li ><a href="{% url 'donate_app:contact' %}">Contact Us</a></li>
		<li ><a href="{% url 'donate_app:faq' %}">FAQ</a></li>
		<li ><a href="{% url 'donate_app:team' %}">Our team</a></li>
		<li><a href="{% url 'user_app:login' %}"><button>Log in</button></a>
		<li><a href="{% url 'user_app:signupform' %}"><button>Sign up</button></a>
	</ul>
	{% endblock %}


<!-- <div class="middle">


	</div> -->
	{% block media_content%}
	<div class="mid">
		<div class="background">
			<nav class="product-filter">
				<h1>Jackets</h1>
				
				<div class="sort">
					<div class="collection-sort">
						<label>Filter by:</label>
						<select>
					  <option value="/">All Jackets</option>
					  <option value="/">2016</option>
					  <option value="/">jacket</option>
					  <option value="/">Jackets</option>
					  <option value="/">layers</option>
					  <option value="/">Obermeyer</option>
					  <option value="/">Roxy</option>
					  <option value="/">womens</option>
					   </select>
					</div>
					
					<div class="collection-sort">
						<label>Sort by:</label>
						<select>
					  <option value="/">Featured</option>
					  <option value="/">Best Selling</option>
					  <option value="/">Alphabetically, A-Z</option>
					  <option value="/">Alphabetically, Z-A</option>
					  <option value="/">Price, low to high</option>
					  <option value="/">Price, high to low</option>
					  <option value="/">Date, new to old</option>
					  <option value="/">Date, old to new</option>
					</select>
					</div>
				</div>
			</nav>
			
			<section class="products">
				<div class="product-card">
					<div class="product-image">
						<img src="https://cdn.shopify.com/s/files/1/0938/8938/products/10231100205_1_1315x1800_300_CMYK_1024x1024.jpeg?v=1445623369">
					</div>
					<div class="product-info">
						<h5>Winter Jacket</h5>
						<h6>$99.99</h6>
					</div>
				</div>
				
				<div class="product-card">
					<div class="product-image">
						<img src="https://cdn.shopify.com/s/files/1/0938/8938/products/10231100205_1_1315x1800_300_CMYK_1024x1024.jpeg?v=1445623369">
					</div>
					<div class="product-info">
						<h5>Winter Jacket</h5>
						<h6>$99.99</h6>
					</div>
				</div>
				
				<div class="product-card">
					<div class="product-image">
						<img src="https://cdn.shopify.com/s/files/1/0938/8938/products/10231100205_1_1315x1800_300_CMYK_1024x1024.jpeg?v=1445623369">
					</div>
					<div class="product-info">
						<h5>Winter Jacket</h5>
						<h6>$99.99</h6>
					</div>
				</div>
				
				<div class="product-card">
					<div class="product-image">
						<img src="https://cdn.shopify.com/s/files/1/0938/8938/products/10231100205_1_1315x1800_300_CMYK_1024x1024.jpeg?v=1445623369">
					</div>
					<div class="product-info">
						<h5>Winter Jacket</h5>
						<h6>$99.99</h6>
					</div>
				</div>
				
				<div class="product-card">
					<div class="product-image">
						<img src="https://cdn.shopify.com/s/files/1/0938/8938/products/10231100205_1_1315x1800_300_CMYK_1024x1024.jpeg?v=1445623369">
					</div>
					<div class="product-info">
						<h5>Winter Jacket</h5>
						<h6>$99.99</h6>
					</div>
				</div>
				
				<div class="product-card">
					<div class="product-image">
						<img src="https://cdn.shopify.com/s/files/1/0938/8938/products/10231100205_1_1315x1800_300_CMYK_1024x1024.jpeg?v=1445623369">
					</div>
					<div class="product-info">
						<h5>Winter Jacket</h5>
						<h6>$99.99</h6>
					</div>
				</div>
				
				<div class="product-card">
					<div class="product-image">
						<img src="https://cdn.shopify.com/s/files/1/0938/8938/products/10231100205_1_1315x1800_300_CMYK_1024x1024.jpeg?v=1445623369">
					</div>
					<div class="product-info">
						<h5>Winter Jacket</h5>
						<h6>$99.99</h6>
					</div>
				</div>
				
				<div class="product-card">
					<div class="product-image">
						<img src="https://cdn.shopify.com/s/files/1/0938/8938/products/10231100205_1_1315x1800_300_CMYK_1024x1024.jpeg?v=1445623369">
					</div>
					<div class="product-info">
						<h5>Winter Jacket</h5>
						<h6>$99.99</h6>
					</div>
				</div>
				
				<div class="product-card">
					<div class="product-image">
						<img src="https://cdn.shopify.com/s/files/1/0938/8938/products/10231100205_1_1315x1800_300_CMYK_1024x1024.jpeg?v=1445623369">
					</div>
					<div class="product-info">
						<h5>Winter Jacket</h5>
						<h6>$99.99</h6>
					</div>
				</div>
				
				<div class="product-card">
					<div class="product-image">
						<img src="https://cdn.shopify.com/s/files/1/0938/8938/products/10231100205_1_1315x1800_300_CMYK_1024x1024.jpeg?v=1445623369">
					</div>
					<div class="product-info">
						<h5>Winter Jacket</h5>
						<h6>$99.99</h6>
					</div>
				</div>
				
		
			</div>
			</div>
	{% endblock %}

	<!--NAVIGATION BAR BOTTOM-->
	<div class="navdown">
		<div class="navdown">
		<ul>	
		<li><a href="#">Terms&Conditions</a></li>
        <li><a href="#">Privacy</a></li>
    </ul>
	</div>

</body>
</html>

donate_app/templates/team.html
{% extends 'base.html' %}
{% load static %}

	{% block css %}
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
		.card {
			padding: 5px;
			margin: 20px;
			float: left;
		 	box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
		 	max-width: 300px;
		 	margin: auto;
		 	text-align: center;
		 	font-family: century gothic;
	   	}
	   
	   	.title {
			color: grey;
		 	font-size: 18px;
	   	}
	</style>
	{% endblock %}
	{% block title %}
	Donate | Team
	{% endblock %}

	


	{% block navbar %}
	<ul>
		<li ><a href="{% url 'donate_app:home' %}">Home</a></li>	
		<li ><a href="{% url 'donate_app:what' %}">What we do</a></li>	
		<li ><a href="{% url 'donate_app:donateform' %}">Donate</a></li>
		<li ><a href="{% url 'donate_app:shop' %}">Shop</a></li>
		<li ><a href="{% url 'donate_app:blogs' %}">Blogs</a></li>
		<li ><a href="{% url 'donate_app:contact' %}">Contact Us</a></li>
		<li ><a href="{% url 'donate_app:faq' %}">FAQ</a></li>
		<li class="active"><a href="{% url 'donate_app:team' %}">Our team</a></li>
		<li><a href="{% url 'user_app:login' %}"><button>Log in</button></a>
		<li><a href="{% url 'user_app:signupform' %}"><button>Sign up</button></a>
	</ul>
	{% endblock %}

{% block media_content %}
<div class="middle">
	<div class="card">
		<img src="../../media/donateApp/img1.jpg" alt="image" style="width:200px; height: 200px;">
		<h1>Shreejit Hora</h1>
		<p class="title">Backend Designer</p>
		<p>Kathford International College</p> 
	</div> 
	<div class="card">
		<img src="../../media/donateApp/img3.jpg" alt="image" style="width:200px; height: 200px;">
		<h1>Sumnima Thapa</h1>
		<p class="title">Content riter</p>
		<p>St.Xaviers College</p>
	</div>
		<img src="../../media/donateApp/img2.jpg" alt="image" style="width:200px; height: 200px;">
		<h1>Utsav Dhungana</h1>
		<p class="title">Frontend Designer</p>
		<p>Asian College</p>
 	</div>

	<div class="card">
		<img src="../../media/donateApp/img4.jpg" alt="image" style="width:200px; height: 200px;">
		<h1>Bijita Kc</h1>
		<p class="title">Frontend Designer</p>
		<p>Kathford International College</p>
 	</div>
</div>
{% endblock %}

user_app/templates/signup.html
{% extends 'base.html' %}
    

{% block media_content %}
<h2 align="center">Create an account</h2>
    <form action="{% url 'user_app:signup' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- <table align="center" width="750">
        
        <tr align="center">
        </tr>
        
        <tr>
            <td align="right">
                <label for="name"><b>Name:</b></label>
            </td>
            <td><input type="text" placeholder="Enter your name" name="name" required/></td>
        </tr>
        
         <tr>
            <td>
                <label for="gender"> <b>Gender:</b> </label><br>
                <input type="radio" name="gender" value="male" checked> Male<br>
                <input type="radio" name="gender" value="female"> Female<br>
                <input type="radio" name="gender" value="other"> Other 
            </td>
         </tr>


        <tr>
            <td align="right"> 
                <label for="email"><b>Email:</b></label>
            </td>

            <td><input type="text" placeholder="Enter your email" name="" required/></td>
        </tr>
        
        <tr>
            <td align="right">
                <label for="name"><b>Password:</b></label></td>
            </td>

            <td><input type="password" placeholder="Enter your password" name="  " required/></td>
        </tr>
                  
        
        <tr align="center">
            <td ><input type="submit" name="  " value="Create Account" /></td>
        </tr>
    
    
    
    </table> -->
    {{form.as_table}}
    <button type="submit">signup</button>

</form>
{% endblock %}

</body>

</html>